# Site settings
title: raulpe7eira
description:
  en: 'Full-Stack Developer of Jaya. SMC, usability expert, cycling enthusiast, who loves family.'
  pt_BR: 'Desenvolvedor Full-Stack Developer da Jaya. CSM, especialista em usabilidade, ciclista entusiasta, que ama a família.'
headline:
  en: 'Full-Stack Developer of <a href="https://jaya.tech/" title="link to Jaya website">Jaya</a>. <a href="https://www.scrumalliance.org/community/profile/rsilva10" title="link to Scrum Master Certified profile">SMC</a>, usability expert, cycling enthusiast, who loves family.'
  pt_BR: 'Desenvolvedor Full-Stack da <a href="https://jaya.tech/" title="link para o site da Jaya">Jaya</a>. <a href="https://www.scrumalliance.org/community/profile/rsilva10" title="link para a Certificação Scrum Master">CSM</a>, especialista em usabilidade, ciclista entusiasta, que ama a família.'
url: 'https://raulpe7eira.tech'
baseurl: ''
google_analytics: 'UA-125091270-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'raulpe7eira'
  email: raul.pereira@gmail.com
  with_blog: false
  # google_plus_username: RaulPereiraSilva
  # twitter_username: raulpe7eira
  # facebook_username: raulpe7eira
  instagram_username: raulpe7eira
  strava_username: raulpe7eira
  github_username:  raulpe7eira
  linkedin_username:  raulpe7eira

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: docs
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

languages: ['en', 'pt_BR']
default_lang: 'en'
exclude_from_localization: ['css', 'fonts', 'images', 'js']
parallel_localization: true
data_dir: /_data
languages_display:
  en:
    label: 'English'
    title: 'Translate to English'
  pt_BR:
    label: 'Português (BR)'
    title: 'Traduzir para Português (BR)'
dates_format:
  en: '%m/%d/%Y'
  pt_BR: '%d/%m/%Y'

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-polyglot', 'jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'index_sample.html']
